# A composition of services that are needed to run the tests of the client
# This is for DEVELOPMENT, not production

version: "3"
services:
  graph-node:
    image: 'graphprotocol/graph-node:v0.17.1'
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
    links:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: postgres:5432
      postgres_user: postgres
      postgres_pass: 'letmein'
      postgres_db: postgres
      ipfs: ipfs:5001
      ethereum: private:http://ganache:8545
      GRAPH_LOG: "graph.log"
      GRAPH_IPFS_TIMEOUT: '2'
      GRAPH_MAX_IPFS_FILE_BYTES: '990000'
      GRAPH_GRAPHQL_MAX_FIRST: '1000'

  ipfs:
    image: daostack/test-env-ipfs:3.0.32
    ports:
      - 5001:5001

  postgres:
    image: daostack/test-env-postgres:3.0.32
    ports:
      - 9432:5432
    environment:
      POSTGRES_PASSWORD: 'letmein'

  ganache:
    image: daostack/test-env-ganache:3.0.32
    ports:
      - 8545:8545
