# A composition of services that are needed to run the tests of the client
# This is for DEVELOPMENT, not production

version: "3"
services:
  graph-node:
    image: 'graphprotocol/graph-node@sha256:8af6adc44d6c55eaed7f6d3ac2b96af0823044e94ffee380288f07e96d5ff30b'
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
    links:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: postgres:5432
      postgres_user: postgres
      postgres_pass: 'letmein'
      postgres_db: postgres
      ipfs: ipfs:5001
      ethereum: private:http://ganache:8545
      GRAPH_LOG: "graph.log"
      GRAPH_GRAPHQL_MAX_FIRST: 1000

  ipfs:
    image: daostack/subgraph-ipfs:0.0.1-rc.31-v0-3.0.13
    ports:
      - 5001:5001

  postgres:
    image: daostack/subgraph-postgres:0.0.1-rc.31-v0-3.0.13
    ports:
      - 9432:5432
    environment:
      POSTGRES_PASSWORD: 'letmein'

  ganache:
    image: daostack/test-env:0.0.1-rc.31-v0-3.0.13
    ports:
      - 8545:8545
