# A composition of services that are needed to run the tests of the client
# This is for DEVELOPMENT, not production

version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node:latest@sha256:b8974ea34ce95aac48d618fa4989bb60474a33c2dfb047fc87111a3283108ba3

    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
    links:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: postgres:5432
      postgres_user: postgres
      postgres_pass: 'letmein'
      postgres_db: postgres
      ipfs: ipfs:5001
      ethereum: development:http://ganache:8545
      GRAPH_LOG: "graph.log"

  ipfs:
    image: daostack/subgraph-ipfs:ganache-0.0.1-rc.11-v3-0.0.2
    ports:
      - 5001:5001

  postgres:
    image: daostack/subgraph-postgres:ganache-0.0.1-rc.11-v3-0.0.2
    ports:
      - 9432:5432
    environment:
      POSTGRES_PASSWORD: 'letmein'

  ganache:
    image: daostack/migration:0.0.1-rc.11-v3
    ports:
      - 8545:8545
    command: >
      --gasLimit 8000000
